# Generated by Django 3.1.13 on 2021-10-24 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MTR', 'Material'), ('PRD', 'Product'), ('CSB', 'Consumable'), ('FBR', 'Fiber'), ('TOL', 'Tool')], max_length=3)),
                ('asset', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleOpenInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=2)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CSM', 'Consume'), ('CVT', 'Convert'), ('TRF', 'Transfer'), ('ITF', 'Interface Movement')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(choices=[('KG', 'kg'), ('LT', 'l')], max_length=2)),
                ('type', models.CharField(choices=[('WGT', 'Weight'), ('VOL', 'Volume')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TransferTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.task')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRT', 'Draft'), ('CRT', 'Created'), ('CTD', 'Completed'), ('DLT', 'Deleted')], max_length=3)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tasktype'),
        ),
        migrations.CreateModel(
            name='SingleOpenInventoryTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_open_inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.singleopeninventory')),
                ('transfer_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.transfertask')),
            ],
        ),
        migrations.CreateModel(
            name='SingleOpenInventoryConsume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.consumetask')),
                ('single_open_inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.singleopeninventory')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.itemtype'),
        ),
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uom'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location'),
        ),
        migrations.CreateModel(
            name='InterfaceMovementTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='ConvertTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='ConvertMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_quantity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('convert_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.converttask')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
            ],
        ),
        migrations.AddField(
            model_name='consumetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.task'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('item', 'location'), name='unique_item_location'),
        ),
    ]
