# Generated by Django 3.1.13 on 2021-10-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.uom'),
        ),
    ]
