# Generated by Django 3.1.13 on 2021-10-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211025_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='uom',
            name='type',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='uom',
            name='uom',
            field=models.CharField(max_length=2),
        ),
    ]
