# Generated by Django 3.1.13 on 2021-11-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211025_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertmaterial',
            name='consume_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
