# Generated by Django 3.1.13 on 2021-11-05 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211104_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.location'),
        ),
    ]
