# Generated by Django 3.1.13 on 2021-11-06 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211105_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertmaterial',
            name='consume_quantity',
        ),
        migrations.CreateModel(
            name='ConvertMaterialConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_quantity', models.FloatField()),
                ('convert_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.convertmaterial')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventory')),
            ],
        ),
    ]
