# Generated by Django 3.1.13 on 2021-11-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211106_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='converttask',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
