# Generated by Django 3.1.13 on 2021-11-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_converttask_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converttask',
            name='quantity',
        ),
    ]
