# Generated by Django 3.1.13 on 2021-11-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_converttask_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='converttask',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
