# Generated by Django 3.1.13 on 2021-11-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_converttask_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertmaterialconsumption',
            old_name='consume_quantity',
            new_name='consume_amount',
        ),
        migrations.RemoveField(
            model_name='consumetask',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='converttask',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='interfacemovementtask',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transfertask',
            name='quantity',
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
