# Generated by Django 3.1.13 on 2021-11-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211119_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertmaterialconsumption',
            name='completely_consumed',
            field=models.BooleanField(default=False),
        ),
    ]
