# Generated by Django 3.1.13 on 2021-11-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_convertmaterialconsumption_completely_consumed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterfaceMovementTask',
            new_name='InterfaceTask',
        ),
    ]
