# Generated by Django 3.1.13 on 2021-11-21 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211119_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleopeninventorytransfer',
            name='single_open_inventory_item',
        ),
        migrations.RemoveField(
            model_name='singleopeninventorytransfer',
            name='transfer_task',
        ),
        migrations.AlterField(
            model_name='consumetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AlterField(
            model_name='convertmaterial',
            name='convert_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.converttask'),
        ),
        migrations.AlterField(
            model_name='convertmaterialconsumption',
            name='convert_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.convertmaterial'),
        ),
        migrations.AlterField(
            model_name='converttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convert_task', to='core.task'),
        ),
        migrations.AlterField(
            model_name='interfacetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='core.task'),
        ),
        migrations.AlterField(
            model_name='transfertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.DeleteModel(
            name='SingleOpenInventoryConsume',
        ),
        migrations.DeleteModel(
            name='SingleOpenInventoryTransfer',
        ),
    ]
