# Generated by Django 3.1.13 on 2021-11-21 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211121_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertmaterialconsumption',
            name='open_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.singleopeninventory'),
        ),
        migrations.AlterField(
            model_name='convertmaterialconsumption',
            name='convert_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_items', to='core.convertmaterial'),
        ),
    ]
