# Generated by Django 3.1.13 on 2021-11-23 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20211123_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
